export enum Socketcom {
  planetUpdate = 'planetUpdate',
  userStateChanged = 'userStateChanged',
  updatePlanetsAndWarehouse = 'updateAll',
  checkCompleteUpgrade = 'checkCompleteUpgrade',
  upgradePlanet = 'upgradePlanet',
  warehouseUpdate = 'warehouseUpdate',
  fetchLeaderboard = 'fetchLeaderboard',
  leaderboardUpdate = 'leaderboardUpdate',
  resolveUserNames = 'resolveUserNames',
  usernamesResolved = 'usernamesResolved',
  UpdateResourceGeneration = 'UpdateResourceGeneration',
  getCounters = 'getCounters',
  counters = 'counters',
  getUser = 'getUser',
  userPageData = 'userPageData',
}
